name: Build, Push and Notify

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag webapp:$(GITHUB_SHA) .

    - name: Login Docker Hub
      run: docker login --username josaphatyoga --password ${{ secrets.DOCKER_TOKEN }}

    - name: Push Image to Docker Image Registry 
      run: docker push 

  notify: 
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_URL }}
        run: |
          curl -H "Content-Type: application/json" -d '{"content": "Image telah berhasil dibuild dan dipush ke Docker Image Registry, Ndoro"}' $DISCORD_WEBHOOK_URL
    
    
